- name: Deploy the cart application
  hosts: cart
  become: yes 
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell:  dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: nodejs install
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: creating user  #ansible user module
    ansible.builtin.user: 
      name: roboshop

  - name: removing directory recrusively
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating a directory # ansible create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the code #ansible download file : Google
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/cart.zip
      dest: /tmp 

  - name: unzipping the code 
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes 

  - name: Install dependencides
    ansible.builtin.command: npm install
    args: 
      chdir: /app

  - name: integrating redis to cart & catalogue server
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: reloading the deamon #ansible deamon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name:  cart enable & start #ansible systemctl module
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes
