- name: Deploy the catalogue application
  hosts: catalogue
  become: yes 
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell:  dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: nodejs install
    ansible.builtin.package:
      name: nodejs
      state: present
