- name: Deploy the catalogue application
  hosts: catalogue
  become: yes 
  tasks:
  - name: disable old nodejs and enable nodejs
    ansible.builtin.shell:  dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: nodejs install
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: creating user  #ansible user module
    ansible.builtin.user: 
      name: roboshop

  - name: creating a directory # ansible create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download the code #ansible download file : Google
    ansible.builtin.get_url:
      url: curl -o /tmp/catalogue.zip https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp 

  - name: unzipping the code 
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app