- name: mysql deployment 
  hosts: mysql 
  become: yes 
  tasks: 
  - name: disable mysql current version 
    ansible.builtin.command: dnf module disable mysql -y 

  - name: downloading the mysql repo
    ansible.builtin.copy: 
      src: mysql.repo
      dest: /etc/yum.repos.d/mysql.repo

  - name: installing mysql server
    ansible.builtin.package:
      name: mysql-community-server
      state: present 

  - name: start and enable mysql 
    ansible.builtin.service: 
      name: mysqld
      state: started
      enabled: yes 

  - name: setup root password 
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
    
