- name: shipping deployment 
  hosts: shipping 
  become: yes 
  tasks: 
  - name: install maven 
    ansible.builtin.package:
      name: maven 
      state: present 

  - name: creating a user 
    ansible.builtin.user: 
      name: roboshop 

  - name: removing the existing directory 
    ansible.builtin.file: 
      path: /app 
      state: absent 

  - name: creating the directory 
    ansible.builtin.file: 
      path: /app 
      state: directory 

  - name: downloading the shipping code 
    ansible.builtin.get_url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp

  - name: unarchiving the file 
    ansible.builtin.unarchive: 
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes 

  - name: install dependicies
    ansible.builtin.command: mvn clean package
    args: 
      chdir: /app

  - name: renamming the jar file 
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args: 
      chdir: /app

  - name: configuring shipping 
    ansible.builtin.copy: 
      src: shipping.conf
      dest: /etc/systemd/system/shipping.service

  - name: reloading the deamon #ansible deamon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable shipping 
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes 

  - name: installing mysql 
    ansible.builtin.package: 
      name: mysql 
      state: present 

  - name: load schema 
    ansible.builtin.shell: mysql -h mysql.techranger.xyz -uroot -pRoboShop@1 < /app/schema/shipping.sql 

  - name: restarted the service
    ansible.builtin.service:
      name: shipping
      state: restarted

